version: 2

sources:
  - name: raw
    database: hive
    schema: raw
    tables:
      - name: nyc_taxi_trips
        description: "NYC Yellow Taxi trip records"
        columns:
          - name: VendorID
            description: "Taxi vendor ID"
            tests:
              - not_null
          - name: tpep_pickup_datetime
            description: "Pickup timestamp"
            tests:
              - not_null
          - name: trip_distance
            description: "Trip distance in miles"
            tests:
              - not_null
          - name: fare_amount
            description: "Base fare"
            tests:
              - not_null
